Repository tarantool/doc, pull requests merged in 2022-02, with the labels that each got.

#2328 Fixes gh-2250 New field - IPROTO_BALLOT_CAN_LEAD
  doc/dev_guide/internals/box_protocol.rst
Labels: 2.10

#2537 Translate SQL features
  doc/reference/reference_sql/sql-features.rst
  locale/ru/LC_MESSAGES/reference/reference_sql/sql-features.po
Labels: localization

#2671 Fixes gh-1687 feedback: Data model
  doc/reference/reference_lua/uuid.rst
  locale/ru/LC_MESSAGES/reference/reference_lua/uuid.po
Labels: 2.10

#2694 Add human-readable anchor link to Python connectors table
  doc/book/connectors/__go.rst
  doc/book/connectors/__python.rst
Labels: teamQ
